# Generated by Django 5.0.3 on 2024-04-07 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_todolist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
